#github-action to validate terraform templates when pull request is raised

name: Terraform

on:
  pull_request

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
