#github-action to validate terraform templates when pull request is raised

name: Terraform

on:
  pull_request

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: false


      - name: Terraform Validate
        run: terraform validate
